# Generated by Django 5.1.4 on 2025-01-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blog_name", models.CharField(max_length=100)),
                ("blog_info", models.TextField()),
                ("blog_date", models.DateTimeField(auto_now_add=True)),
                ("blog_image", models.ImageField(upload_to="blog_img")),
            ],
        ),
    ]
