# Generated by Django 5.1.4 on 2025-01-31 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="blog_image",
            field=models.ImageField(upload_to="public/static/blog_img"),
        ),
    ]
