# Generated by Django 5.1.4 on 2025-01-31 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_alter_book_blog_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="blog_image",
            field=models.ImageField(upload_to="blog_imges"),
        ),
    ]
