# Generated by Django 5.1.4 on 2025-01-31 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_alter_book_blog_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="blog_image",
            field=models.ImageField(upload_to="blog_images"),
        ),
    ]
