# Generated by Django 5.1.4 on 2025-01-31 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0005_alter_book_blog_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blog_name", models.CharField(max_length=100)),
                ("blog_info", models.TextField()),
                ("blog_date", models.DateTimeField(blank=True, null=True)),
                ("blog_image", models.ImageField(upload_to="blog_images")),
            ],
        ),
        migrations.DeleteModel(
            name="book",
        ),
    ]
